# Generated by Django 6.0 on 2025-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
