# Generated by Django 6.0 on 2025-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
